spring.application.name=LittleDelhiBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/littledelhi
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
